// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Event struct {
	ID       string `json:"id"`
	Request  string `json:"request"`
	Browser  string `json:"browser"`
	Os       string `json:"os"`
	Device   string `json:"device"`
	City     string `json:"city"`
	Country  string `json:"country"`
	CreateAt string `json:"create_at"`
}

type EventsList struct {
	Events []*Event `json:"events"`
}

type Filter struct {
	Page *int `json:"page"`
	Size *int `json:"size"`
}
